/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugas4;

import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.WARNING_MESSAGE;


/**
 *
 * @author andrew
 */
public class Cuaca extends javax.swing.JFrame {

    /**
     * Creates new form FormCuaca
     */
    public Cuaca() {
        initComponents();
        
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbHari = new javax.swing.JComboBox<>();
        monitorCuaca = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        copyHari = new javax.swing.JLabel();
        hasilSuhu = new javax.swing.JLabel();
        Maks = new javax.swing.JLabel();
        Min = new javax.swing.JLabel();
        Angin = new javax.swing.JLabel();
        Lembap = new javax.swing.JLabel();
        Tekanan = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        hasilKota = new javax.swing.JTextField();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuExit = new javax.swing.JMenuItem();
        menuAbout = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setTitle("Monitor Cuaca");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cbHari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hari ini", "Besok" }));
        cbHari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbHariActionPerformed(evt);
            }
        });

        monitorCuaca.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        monitorCuaca.setText("Monitor Cuaca");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Suhu Maksimum");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Suhu Minimum");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Kecepatan Angin");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Kelembapan");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Tekanan Udara");

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 2, 11)); // NOI18N
        jLabel9.setText("broken clouds");

        copyHari.setText("         ");

        hasilSuhu.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        hasilSuhu.setText("          ");

        Maks.setText("   ");

        Min.setText("       ");

        Angin.setText("         ");

        Lembap.setText("       ");

        Tekanan.setText("    ");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas4/04n.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(hasilSuhu, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(copyHari, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(43, 43, 43)
                                                .addComponent(Angin))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(Min, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(Lembap, javax.swing.GroupLayout.Alignment.TRAILING)))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Maks, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Tekanan)))))
                        .addGap(0, 59, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(monitorCuaca)
                        .addGap(133, 133, 133)
                        .addComponent(cbHari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbHari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(monitorCuaca))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(copyHari)
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Min))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Angin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(Lembap)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hasilSuhu)
                            .addComponent(jLabel3)
                            .addComponent(Maks))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(Tekanan))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Kota");

        hasilKota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilKotaActionPerformed(evt);
            }
        });

        jMenu4.setText("File");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem4.setText("Exit");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuBar2.add(jMenu4);

        jMenu5.setText("Help/Input Data Baru");

        menuExit.setText("Help");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        jMenu5.add(menuExit);

        menuAbout.setText("About");
        menuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAboutActionPerformed(evt);
            }
        });
        jMenu5.add(menuAbout);

        jMenuItem1.setText("Input");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        jMenuItem2.setText("Data");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem2);

        jMenuBar2.add(jMenu5);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hasilKota, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(hasilKota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        // TODO add your handling code here:
        FormHelp help = new FormHelp();
        help.setVisible(true);
    }//GEN-LAST:event_menuExitActionPerformed

    private void menuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAboutActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Aplikasi Monitoring Cuaca" + "\n Andrew S.C Manurung" + "\n NIM 1641913");
    }//GEN-LAST:event_menuAboutActionPerformed

    private void hasilKotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilKotaActionPerformed
        String Hari = (String) cbHari.getSelectedItem();
        copyHari.setText(Hari);
        
        if("Hari ini".equals(copyHari.getText()) && "jakarta".equals(hasilKota.getText())){
            hasilSuhu.setText("20.3 " + (char)0x00B0 + "C");
            monitorCuaca.setText("Cuaca di Jakarta");
            copyHari.setText("Hari ini");
            Maks.setText("30.0 " + (char)0x00B0 + "C");
            Min.setText("10.0 " + (char)0x00B0 + "C");
            Angin.setText("20.0 m/s");
            Lembap.setText("200.2 %");
            Tekanan.setText("200.2 hPa");   
        }else if("Besok".equals(copyHari.getText()) && "jakarta".equals(hasilKota.getText())){
            hasilSuhu.setText("28.3 " + (char)0x00B0 + "C");
            monitorCuaca.setText("Cuaca di Jakarta");
            copyHari.setText("Besok");
            Maks.setText("32.0 " + (char)0x00B0 + "C");
            Min.setText("20.0 " + (char)0x00B0 + "C");
            Angin.setText("80.0 m/s");
            Lembap.setText("20.2 %");
            Tekanan.setText("20.2 hPa");   
        }else if("Hari ini".equals(copyHari.getText()) && "bandung".equals(hasilKota.getText())){
            hasilSuhu.setText("20.3 " + (char)0x00B0 + "C");
            monitorCuaca.setText("Cuaca di Bandung");
            copyHari.setText("Hari ini");
            Maks.setText("30.0 " + (char)0x00B0 + "C");
            Min.setText("10.0 " + (char)0x00B0 + "C");
            Angin.setText("20.0 m/s");
            Lembap.setText("200.2 %");
            Tekanan.setText("200.2 hPa");  
        }else if("Besok".equals(copyHari.getText()) && "bandung".equals(hasilKota.getText())){
            hasilSuhu.setText("18.3 " + (char)0x00B0 + "C");
            monitorCuaca.setText("Cuaca di Bandung");
            copyHari.setText("Besok");
            Maks.setText("40.0 " + (char)0x00B0 + "C");
            Min.setText("10.0 " + (char)0x00B0 + "C");
            Angin.setText("20.0 m/s");
            Lembap.setText("210.2 %");
            Tekanan.setText("210.2 hPa");  
        }else if("Hari ini".equals(copyHari.getText()) && "surabaya".equals(hasilKota.getText())){
            hasilSuhu.setText("40.3 " + (char)0x00B0 + "C");
            monitorCuaca.setText("Cuaca di Surabaya");
            copyHari.setText("Hari ini");
            Maks.setText("30.0 " + (char)0x00B0 + "C");
            Min.setText("10.0 " + (char)0x00B0 + "C");
            Angin.setText("20.0 m/s");
            Lembap.setText("200.2 %");
            Tekanan.setText("200.2 hPa");
        }else if("Besok".equals(copyHari.getText()) && "surabaya".equals(hasilKota.getText())){
            hasilSuhu.setText("37.3 " + (char)0x00B0 + "C");
            monitorCuaca.setText("Cuaca di Surabaya");
            copyHari.setText("Besok");
            Maks.setText("38.0 " + (char)0x00B0 + "C");
            Min.setText("30.0 " + (char)0x00B0 + "C");
            Angin.setText("20.0 m/s");
            Lembap.setText("222.2 %");
            Tekanan.setText("222.2 hPa");
        }else{
            JOptionPane.showMessageDialog(null, "Kota " + hasilKota.getText() +" tidak ditemukan", "Kota tidak ditemukan", WARNING_MESSAGE);
        }
    }//GEN-LAST:event_hasilKotaActionPerformed

    private void cbHariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbHariActionPerformed
        // TODO add your handling code here:
        String Hari = (String) cbHari.getSelectedItem();
        copyHari.setText(Hari);
        
        if("Hari ini".equals(copyHari.getText()) && "jakarta".equals(hasilKota.getText())){
            hasilSuhu.setText("20.3 " + (char)0x00B0 + "C");
            monitorCuaca.setText("Cuaca di Jakarta");
            copyHari.setText("Hari ini");
            Maks.setText("30.0" + (char)0x00B0 + " C");
            Min.setText("10.0 " + (char)0x00B0 + " C");
            Angin.setText("20.0 m/s");
            Lembap.setText("200.2 %");
            Tekanan.setText("200.2 hPa");   
        }else if("Besok".equals(copyHari.getText()) && "jakarta".equals(hasilKota.getText())){
            hasilSuhu.setText("28.3 " + (char)0x00B0 + "C");
            monitorCuaca.setText("Cuaca di Jakarta");
            copyHari.setText("Besok");
            Maks.setText("32.0 " + (char)0x00B0 + "C");
            Min.setText("20.0 " + (char)0x00B0 + "C");
            Angin.setText("80.0 m/s");
            Lembap.setText("20.2 %");
            Tekanan.setText("20.2 hPa");   
        }else if("Hari ini".equals(copyHari.getText()) && "bandung".equals(hasilKota.getText())){
            hasilSuhu.setText("20.3 " + (char)0x00B0 + "C");
            monitorCuaca.setText("Cuaca di Bandung");
            copyHari.setText("Hari ini");
            Maks.setText("30.0 " + (char)0x00B0 + "C");
            Min.setText("10.0 " + (char)0x00B0 + "C");
            Angin.setText("20.0 m/s");
            Lembap.setText("200.2 %");
            Tekanan.setText("200.2 hPa");  
        }else if("Besok".equals(copyHari.getText()) && "bandung".equals(hasilKota.getText())){
            hasilSuhu.setText("18.3 " + (char)0x00B0 + "C");
            monitorCuaca.setText("Cuaca di Bandung");
            copyHari.setText("Besok");
            Maks.setText("40.0 " + (char)0x00B0 + "C");
            Min.setText("10.0 " + (char)0x00B0 + "C");
            Angin.setText("20.0 m/s");
            Lembap.setText("210.2 %");
            Tekanan.setText("210.2 hPa");  
        }else if("Hari ini".equals(copyHari.getText()) && "surabaya".equals(hasilKota.getText())){
            hasilSuhu.setText("40.3 " + (char)0x00B0 + "C");
            monitorCuaca.setText("Cuaca di Surabaya");
            copyHari.setText("Hari ini");
            Maks.setText("30.0 " + (char)0x00B0 + "C");
            Min.setText("10.0 " + (char)0x00B0 + "C");
            Angin.setText("20.0 m/s");
            Lembap.setText("200.2 %");
            Tekanan.setText("200.2 hPa");
        }else if("Besok".equals(copyHari.getText()) && "surabaya".equals(hasilKota.getText())){
            hasilSuhu.setText("37.3 " + (char)0x00B0 + "C");
            monitorCuaca.setText("Cuaca di Surabaya");
            copyHari.setText("Besok");
            Maks.setText("38.0 " + (char)0x00B0 + "C");
            Min.setText("30.0 " + (char)0x00B0 + "C");
            Angin.setText("20.0 m/s");
            Lembap.setText("222.2 %");
            Tekanan.setText("222.2 hPa");
        }else{
            JOptionPane.showMessageDialog(null, "Kota " + hasilKota.getText() +" tidak ditemukan", "Kota tidak ditemukan", WARNING_MESSAGE);
        }
    }//GEN-LAST:event_cbHariActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        System.exit(-1);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       FormInputData input = new FormInputData();
       input.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        FormData input = new FormData();
        input.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        

        

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cuaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Cuaca().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Angin;
    private javax.swing.JLabel Lembap;
    private javax.swing.JLabel Maks;
    private javax.swing.JLabel Min;
    private javax.swing.JLabel Tekanan;
    private javax.swing.JComboBox<String> cbHari;
    private javax.swing.JLabel copyHari;
    private javax.swing.JTextField hasilKota;
    private javax.swing.JLabel hasilSuhu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem menuAbout;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JLabel monitorCuaca;
    // End of variables declaration//GEN-END:variables
}
